// Static fallback data — used when the API returns empty results or is unavailable
// Public-facing pages always show content, even if the database isn't connected.

export const STATIC_SERVICES = [
  { id: 1, title: "Custom Software Development", description: "Tailor-made software solutions built to meet your exact business needs.", icon: "Code", category: "Development", features: ["Web Apps", "Mobile Apps", "API Integration", "Cloud-native"], isActive: true, createdAt: "" },
  { id: 2, title: "Cloud Infrastructure & DevOps", description: "Scalable, secure cloud architecture and CI/CD pipeline automation.", icon: "Cloud", category: "Infrastructure", features: ["AWS/GCP/Azure", "Kubernetes", "Terraform", "24/7 Monitoring"], isActive: true, createdAt: "" },
  { id: 3, title: "AI & Machine Learning", description: "Intelligent automation and predictive analytics powered by cutting-edge ML.", icon: "Brain", category: "AI", features: ["NLP Models", "Computer Vision", "Data Pipelines", "Model Deployment"], isActive: true, createdAt: "" },
  { id: 4, title: "Cybersecurity", description: "Comprehensive security audits, penetration testing, and compliance management.", icon: "Shield", category: "Security", features: ["Pen Testing", "SOC 2 Compliance", "Threat Detection", "Zero Trust"], isActive: true, createdAt: "" },
  { id: 5, title: "UI/UX Design", description: "User-first design systems and stunning interfaces that convert.", icon: "Palette", category: "Design", features: ["Figma Prototypes", "Design Systems", "User Research", "Accessibility"], isActive: true, createdAt: "" },
  { id: 6, title: "IT Consulting", description: "Strategic technology guidance to transform and future-proof your business.", icon: "Lightbulb", category: "Consulting", features: ["Digital Strategy", "Tech Audits", "Roadmapping", "CTO as a Service"], isActive: true, createdAt: "" },
];

export const STATIC_PORTFOLIO = [
  { id: 1, title: "FinTech Payment Gateway", description: "Real-time payment processing platform handling $2B+ annual transactions.", category: "Fintech", technologies: ["Node.js", "React", "PostgreSQL", "Redis", "Stripe"], imageUrl: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800", clientName: "PaySwift Inc.", isFeatured: true, projectUrl: null, createdAt: "" },
  { id: 2, title: "AI-Powered Supply Chain", description: "Predictive inventory management reducing stockouts by 78% using ML.", category: "AI/ML", technologies: ["Python", "TensorFlow", "FastAPI", "React", "AWS"], imageUrl: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800", clientName: "LogiTech Corp", isFeatured: true, projectUrl: null, createdAt: "" },
  { id: 3, title: "Healthcare SaaS Platform", description: "HIPAA-compliant patient management system serving 500+ clinics.", category: "Healthcare", technologies: ["Next.js", "Django", "PostgreSQL", "Docker", "Kubernetes"], imageUrl: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800", clientName: "MediCore Solutions", isFeatured: true, projectUrl: null, createdAt: "" },
  { id: 4, title: "E-Commerce Marketplace", description: "Multi-vendor marketplace with real-time inventory and AI recommendations.", category: "E-Commerce", technologies: ["React", "Node.js", "MongoDB", "Elasticsearch", "Stripe"], imageUrl: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800", clientName: "ShopBridge Ltd.", isFeatured: false, projectUrl: null, createdAt: "" },
  { id: 5, title: "Real Estate Platform", description: "Property listing platform with AR virtual tours and smart pricing.", category: "PropTech", technologies: ["React Native", "Three.js", "Python", "AWS S3"], imageUrl: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800", clientName: "HomeSmart Realty", isFeatured: false, projectUrl: null, createdAt: "" },
  { id: 6, title: "EdTech Learning Platform", description: "Adaptive learning system with AI-driven personalized curricula.", category: "EdTech", technologies: ["Vue.js", "Django", "PostgreSQL", "WebRTC", "ML"], imageUrl: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=800", clientName: "EduNova Academy", isFeatured: false, projectUrl: null, createdAt: "" },
];

export const STATIC_TESTIMONIALS = [
  { id: 1, clientName: "Jessica Williams", role: "CTO", company: "NovaTech Inc.", rating: 5, content: "SOFTWORKS transformed our legacy systems into a modern cloud infrastructure. Our deployment frequency went from monthly to daily.", avatarUrl: "https://randomuser.me/api/portraits/women/44.jpg", isActive: true, createdAt: "" },
  { id: 2, clientName: "David Kim", role: "VP Engineering", company: "FinanceEdge", rating: 5, content: "The AI-powered fraud detection system they built has saved us millions. The team is incredibly professional and skilled.", avatarUrl: "https://randomuser.me/api/portraits/men/32.jpg", isActive: true, createdAt: "" },
  { id: 3, clientName: "Priya Sharma", role: "CEO", company: "HealthBridge", rating: 5, content: "From concept to launch in 4 months. SOFTWORKS delivered a HIPAA-compliant platform that our doctors love.", avatarUrl: "https://randomuser.me/api/portraits/women/65.jpg", isActive: true, createdAt: "" },
];

export const STATIC_TEAM = [
  { id: 1, name: "Rajan Kapoor", role: "Founder & CEO", department: "Leadership", bio: "15+ years building enterprise software. Previously at Google and Microsoft.", avatarUrl: "https://randomuser.me/api/portraits/men/75.jpg", skills: ["Strategy", "Product", "Leadership"], linkedinUrl: "https://linkedin.com", isActive: true, createdAt: "" },
  { id: 2, name: "Dr. Arjun Mehta", role: "Chief AI Officer", department: "AI & Research", bio: "PhD in Machine Learning from MIT. Led AI initiatives at Amazon.", avatarUrl: "https://randomuser.me/api/portraits/men/45.jpg", skills: ["Machine Learning", "Deep Learning", "Python", "Research"], linkedinUrl: "https://linkedin.com", isActive: true, createdAt: "" },
  { id: 3, name: "Sarah Okonkwo", role: "Head of Cloud", department: "Infrastructure", bio: "AWS and GCP certified architect with 10 years of DevOps experience.", avatarUrl: "https://randomuser.me/api/portraits/women/52.jpg", skills: ["AWS", "Kubernetes", "Terraform", "DevOps"], linkedinUrl: "https://linkedin.com", isActive: true, createdAt: "" },
  { id: 4, name: "Marcus Chen", role: "Security Lead", department: "Cybersecurity", bio: "CISSP certified with background in government cybersecurity.", avatarUrl: "https://randomuser.me/api/portraits/men/36.jpg", skills: ["Penetration Testing", "SIEM", "Compliance", "Zero Trust"], linkedinUrl: "https://linkedin.com", isActive: true, createdAt: "" },
];

export const STATIC_BLOG = [
  { id: 1, title: "The Future of AI in Enterprise Software", slug: "future-ai-enterprise-software", excerpt: "How artificial intelligence is reshaping the enterprise software landscape in 2025.", content: "Artificial intelligence is no longer a buzzword — it is the foundation of modern enterprise software.", category: "AI & Technology", tags: ["AI", "Enterprise", "Machine Learning"], imageUrl: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800", authorName: "Dr. Arjun Mehta", isPublished: true, publishedAt: "2025-03-15T00:00:00.000Z", createdAt: "" },
  { id: 2, title: "Cloud-Native Architecture Best Practices", slug: "cloud-native-architecture-best-practices", excerpt: "Building resilient, scalable applications using microservices and Kubernetes.", content: "Cloud-native architecture is a design approach that embraces the principles of scalability and resilience.", category: "Cloud & DevOps", tags: ["Cloud", "Kubernetes", "DevOps"], imageUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800", authorName: "Sarah Okonkwo", isPublished: true, publishedAt: "2025-02-20T00:00:00.000Z", createdAt: "" },
  { id: 3, title: "Zero Trust Security: A Practical Guide", slug: "zero-trust-security-practical-guide", excerpt: "Implementing zero trust architecture to protect modern distributed systems.", content: "Zero trust is a security model that requires strict identity verification for every person and device.", category: "Cybersecurity", tags: ["Security", "Zero Trust", "Compliance"], imageUrl: "https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=800", authorName: "Marcus Chen", isPublished: true, publishedAt: "2025-01-10T00:00:00.000Z", createdAt: "" },
];

export const STATIC_SAAS = [
  { id: 1, name: "TaskFlow Pro", description: "AI-powered project management for distributed tech teams.", category: "Productivity", status: "active", features: ["AI Task Prioritization", "Time Tracking", "Gantt Charts", "Slack Integration"], pricingMonthly: "29", pricingYearly: "290", demoUrl: "https://taskflow.softworks.com", isActive: true, createdAt: "" },
  { id: 2, name: "SecureVault", description: "Enterprise password and secrets manager with zero-knowledge encryption.", category: "Security", status: "active", features: ["Zero-Knowledge", "SSO Integration", "Audit Logs", "API Access"], pricingMonthly: "49", pricingYearly: "490", demoUrl: "https://vault.softworks.com", isActive: true, createdAt: "" },
  { id: 3, name: "DataSight", description: "Real-time business intelligence dashboard for engineering metrics.", category: "Analytics", status: "beta", features: ["Real-time Dashboards", "Custom Metrics", "Alerts", "API Integrations"], pricingMonthly: "79", pricingYearly: "790", demoUrl: "https://datasight.softworks.com", isActive: true, createdAt: "" },
];
