import { Router, type IRouter } from "express";
import authRouter from "./auth";
import healthRouter from "./health";
import servicesRouter from "./services";
import portfolioRouter from "./portfolio";
import blogRouter from "./blog";
import leadsRouter from "./leads";
import testimonialsRouter from "./testimonials";
import teamRouter from "./team";
import saasRouter from "./saas";
import employeesRouter from "./employees";
import attendanceRouter from "./attendance";
import leavesRouter from "./leaves";
import payrollRouter from "./payroll";
import projectsRouter from "./projects";
import clientsRouter from "./clients";
import dashboardRouter from "./dashboard";
import licensesRouter from "./licenses";
import paymentMethodsRouter from "./paymentMethods";
import faqsRouter from "./faqs";
import invoicesRouter from "./invoices";
import jobsRouter from "./jobs";
import newsletterRouter from "./newsletter";
import { openaiRouter } from "./openai";
import { voiceCallsRouter } from "./voiceCalls";
import { siteSettingsRouter } from "./siteSettings";
import auditLogsRouter from "./auditLogs";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(servicesRouter);
router.use(portfolioRouter);
router.use(blogRouter);
router.use(leadsRouter);
router.use(testimonialsRouter);
router.use(teamRouter);
router.use(saasRouter);
router.use(employeesRouter);
router.use(attendanceRouter);
router.use(leavesRouter);
router.use(payrollRouter);
router.use(projectsRouter);
router.use(clientsRouter);
router.use(dashboardRouter);
router.use(licensesRouter);
router.use(paymentMethodsRouter);
router.use(faqsRouter);
router.use(invoicesRouter);
router.use(jobsRouter);
router.use(newsletterRouter);
router.use("/openai", openaiRouter);
router.use("/voice-calls", voiceCallsRouter);
router.use(siteSettingsRouter);
router.use(auditLogsRouter);

export default router;
